# This is Cloud-Installer template of Websoft9
# Task priority: pre_tasks > role > tasks > post_task
# Variable priority: vars_files > vars

- name: Ansible
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
  
  pre_tasks:
    - copy:
        src: package
        dest: /data/apps/ansible
        force: yes

    roles:
    - {role: role_common, tags: "role_common"}  
    - {role: role_cloud, tags: "role_cloud"}  
    - {role: role_python, tags: "role_python"}   
    - {role: ansible, tags: "ansible"}
    - {role: role_preend, tags: "preend"}
    - {role: role_end, tags: "role_end"}